import React from 'react';
import { Investigation } from '../../types';
import { FileText, ShieldAlert } from 'lucide-react';

interface InvestigationReportProps {
  investigation: Investigation;
}

export const InvestigationReport: React.FC<InvestigationReportProps> = ({ investigation }) => {
  return (
    <div className="max-w-4xl mx-auto fg-card-glow p-8 rounded-2xl border-cyan-500/40 shadow-2xl space-y-6">
      <div className="flex items-center justify-between pb-4 border-b border-[#1E2945]">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center">
            <FileText className="w-5 h-5 text-cyan-400" />
          </div>
          <div>
            <h3 className="font-extrabold text-xl text-white tracking-wide">
              FIN GUARD INVESTIGATION DOSSIER
            </h3>
            <p className="text-xs text-slate-400 font-mono">
              Official AI Security Artifact &bull; Ref: {investigation.id}
            </p>
          </div>
        </div>

        <div className="px-4 py-2 rounded-xl bg-red-950 text-red-400 border border-red-800 text-xs font-mono font-extrabold tracking-wider">
          {investigation.dossierStatus}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs">
        {/* Section 1: Transaction Details */}
        <div className="p-4 rounded-xl bg-[#070A12] border border-[#1E2945] space-y-2">
          <span className="text-cyan-400 font-mono font-bold uppercase text-[11px] block">1. TRANSACTION DETAILS</span>
          <div className="space-y-1 font-mono text-slate-300">
            <div>Txn ID: <strong className="text-white">{investigation.transactionId}</strong></div>
            <div>Customer: <strong className="text-white">{investigation.customer.name} ({investigation.customer.id})</strong></div>
            <div>Amount: <strong className="text-cyan-300 font-bold">{investigation.transaction.amount}</strong></div>
            <div>Merchant: {investigation.transaction.merchant}</div>
            <div>Time: {investigation.transaction.time}</div>
          </div>
        </div>

        {/* Section 2: Risk Level */}
        <div className="p-4 rounded-xl bg-[#070A12] border border-[#1E2945] space-y-2">
          <span className="text-cyan-400 font-mono font-bold uppercase text-[11px] block">2. RISK EVALUATION</span>
          <div className="space-y-1 font-mono">
            <div className="text-2xl font-extrabold text-red-400">{investigation.riskScore}% RISK RATING</div>
            <div className="text-slate-300">Classification: <strong className="text-red-400">{investigation.riskLevel} ANOMALY</strong></div>
            <div className="text-slate-400 text-[11px]">Neural Engine Confidence: 99.4%</div>
          </div>
        </div>

        {/* Section 3: Key Evidence */}
        <div className="p-4 rounded-xl bg-[#070A12] border border-[#1E2945] space-y-2">
          <span className="text-cyan-400 font-mono font-bold uppercase text-[11px] block">3. KEY EVIDENCE VECTORS</span>
          <ul className="space-y-1 text-slate-300 list-disc list-inside">
            {investigation.report.evidenceSummary.map((item, idx) => (
              <li key={idx}>{item}</li>
            ))}
          </ul>
        </div>

        {/* Section 4: AI Recommendation */}
        <div className="p-4 rounded-xl bg-[#070A12] border border-[#1E2945] space-y-2">
          <span className="text-cyan-400 font-mono font-bold uppercase text-[11px] block">4. AI RECOMMENDATION</span>
          <div className="p-2.5 rounded bg-red-950/40 border border-red-500/30 font-mono text-red-300 font-bold">
            {investigation.recommendation}
          </div>
          <p className="text-[11px] text-slate-400">
            PRISM reliability check passed. Evidence fully grounded in raw logs.
          </p>
        </div>
      </div>

      <div className="pt-4 border-t border-[#1E2945] flex items-center justify-between text-[11px] text-slate-500 font-mono">
        <span>Generated by FinGuard Core LLM &bull; Branch: soumen</span>
        <span>Cryptographic Hash: 0x9f8b...41e2</span>
      </div>
    </div>
  );
};
